/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1"
	scheme "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JinghzhusGetter has a method to return a JinghzhuInterface.
// A group's client should implement this interface.
type JinghzhusGetter interface {
	Jinghzhus(namespace string) JinghzhuInterface
}

// JinghzhuInterface has methods to work with Jinghzhu resources.
type JinghzhuInterface interface {
	Create(ctx context.Context, jinghzhu *v1.Jinghzhu, opts metav1.CreateOptions) (*v1.Jinghzhu, error)
	Update(ctx context.Context, jinghzhu *v1.Jinghzhu, opts metav1.UpdateOptions) (*v1.Jinghzhu, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Jinghzhu, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.JinghzhuList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Jinghzhu, err error)
	JinghzhuExpansion
}

// jinghzhus implements JinghzhuInterface
type jinghzhus struct {
	client rest.Interface
	ns     string
}

// newJinghzhus returns a Jinghzhus
func newJinghzhus(c *JinghzhuV1Client, namespace string) *jinghzhus {
	return &jinghzhus{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jinghzhu, and returns the corresponding jinghzhu object, and an error if there is any.
func (c *jinghzhus) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Jinghzhu, err error) {
	result = &v1.Jinghzhu{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jinghzhus").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Jinghzhus that match those selectors.
func (c *jinghzhus) List(ctx context.Context, opts metav1.ListOptions) (result *v1.JinghzhuList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.JinghzhuList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jinghzhus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jinghzhus.
func (c *jinghzhus) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jinghzhus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a jinghzhu and creates it.  Returns the server's representation of the jinghzhu, and an error, if there is any.
func (c *jinghzhus) Create(ctx context.Context, jinghzhu *v1.Jinghzhu, opts metav1.CreateOptions) (result *v1.Jinghzhu, err error) {
	result = &v1.Jinghzhu{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jinghzhus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jinghzhu).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a jinghzhu and updates it. Returns the server's representation of the jinghzhu, and an error, if there is any.
func (c *jinghzhus) Update(ctx context.Context, jinghzhu *v1.Jinghzhu, opts metav1.UpdateOptions) (result *v1.Jinghzhu, err error) {
	result = &v1.Jinghzhu{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jinghzhus").
		Name(jinghzhu.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jinghzhu).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the jinghzhu and deletes it. Returns an error if one occurs.
func (c *jinghzhus) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jinghzhus").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jinghzhus) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jinghzhus").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched jinghzhu.
func (c *jinghzhus) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Jinghzhu, err error) {
	result = &v1.Jinghzhu{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jinghzhus").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
