/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	jinghzhuv1 "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJinghzhus implements JinghzhuInterface
type FakeJinghzhus struct {
	Fake *FakeJinghzhuV1
	ns   string
}

var jinghzhusResource = schema.GroupVersionResource{Group: "jinghzhu.com", Version: "v1", Resource: "jinghzhus"}

var jinghzhusKind = schema.GroupVersionKind{Group: "jinghzhu.com", Version: "v1", Kind: "Jinghzhu"}

// Get takes name of the jinghzhu, and returns the corresponding jinghzhu object, and an error if there is any.
func (c *FakeJinghzhus) Get(ctx context.Context, name string, options v1.GetOptions) (result *jinghzhuv1.Jinghzhu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jinghzhusResource, c.ns, name), &jinghzhuv1.Jinghzhu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jinghzhuv1.Jinghzhu), err
}

// List takes label and field selectors, and returns the list of Jinghzhus that match those selectors.
func (c *FakeJinghzhus) List(ctx context.Context, opts v1.ListOptions) (result *jinghzhuv1.JinghzhuList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jinghzhusResource, jinghzhusKind, c.ns, opts), &jinghzhuv1.JinghzhuList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &jinghzhuv1.JinghzhuList{ListMeta: obj.(*jinghzhuv1.JinghzhuList).ListMeta}
	for _, item := range obj.(*jinghzhuv1.JinghzhuList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jinghzhus.
func (c *FakeJinghzhus) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jinghzhusResource, c.ns, opts))

}

// Create takes the representation of a jinghzhu and creates it.  Returns the server's representation of the jinghzhu, and an error, if there is any.
func (c *FakeJinghzhus) Create(ctx context.Context, jinghzhu *jinghzhuv1.Jinghzhu, opts v1.CreateOptions) (result *jinghzhuv1.Jinghzhu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jinghzhusResource, c.ns, jinghzhu), &jinghzhuv1.Jinghzhu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jinghzhuv1.Jinghzhu), err
}

// Update takes the representation of a jinghzhu and updates it. Returns the server's representation of the jinghzhu, and an error, if there is any.
func (c *FakeJinghzhus) Update(ctx context.Context, jinghzhu *jinghzhuv1.Jinghzhu, opts v1.UpdateOptions) (result *jinghzhuv1.Jinghzhu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jinghzhusResource, c.ns, jinghzhu), &jinghzhuv1.Jinghzhu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jinghzhuv1.Jinghzhu), err
}

// Delete takes name of the jinghzhu and deletes it. Returns an error if one occurs.
func (c *FakeJinghzhus) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jinghzhusResource, c.ns, name), &jinghzhuv1.Jinghzhu{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJinghzhus) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jinghzhusResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &jinghzhuv1.JinghzhuList{})
	return err
}

// Patch applies the patch and returns the patched jinghzhu.
func (c *FakeJinghzhus) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *jinghzhuv1.Jinghzhu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jinghzhusResource, c.ns, name, pt, data, subresources...), &jinghzhuv1.Jinghzhu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jinghzhuv1.Jinghzhu), err
}
