/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	jinghzhuv1 "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1"
	versioned "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1/apis/clientset/versioned"
	internalinterfaces "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1/apis/informers/externalversions/internalinterfaces"
	v1 "github.com/jinghzhu/KubernetesCRD/pkg/crd/jinghzhu/v1/apis/listers/jinghzhu/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// JinghzhuInformer provides access to a shared informer and lister for
// Jinghzhus.
type JinghzhuInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.JinghzhuLister
}

type jinghzhuInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJinghzhuInformer constructs a new informer for Jinghzhu type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJinghzhuInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJinghzhuInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJinghzhuInformer constructs a new informer for Jinghzhu type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJinghzhuInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JinghzhuV1().Jinghzhus(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JinghzhuV1().Jinghzhus(namespace).Watch(context.TODO(), options)
			},
		},
		&jinghzhuv1.Jinghzhu{},
		resyncPeriod,
		indexers,
	)
}

func (f *jinghzhuInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJinghzhuInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *jinghzhuInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jinghzhuv1.Jinghzhu{}, f.defaultInformer)
}

func (f *jinghzhuInformer) Lister() v1.JinghzhuLister {
	return v1.NewJinghzhuLister(f.Informer().GetIndexer())
}
